### ISSUE TITLE
Error loading syntax file

### ISSUE THREAD

**Issue by Jahrme** [daverosoff/MBXTools#30]
After installing `MBXTools` through Sublime's package manager, I am getting the following error:

<img width="534" alt="Error loading syntax file..." src="https://user-images.githubusercontent.com/14228780/37616510-6d7f9532-2b6d-11e8-930a-762394209969.png">

My system:
- macOS 10.13.3
- Sublime Text 3, Build 3143

**Comment by daverosoff** [comment]
Thanks for the report, Jahrme. I believe this issue is due to the package name change. As you can see, its name in Package Control is still MBXTools. There has been a technical issue with the name change that I hope will be resolved in the next few days. In the meantime, the easiest way to keep working would be to uninstall the package from Package Control and install manually via `git` for the time being. I'll update here and in the PreTeXt support group when the naming issue is resolved.

**Comment by Jahrme** [comment]
No worries, just though I should let you know in case you were not aware.

**Comment by daverosoff** [comment]
The name change has gone through. I am not sure what will happen when you open Sublime Text; you still might have to uninstall and reinstall via Package Control. Please let me know what happens next time you open ST!

**Comment by daverosoff** [comment]
I believe the name change has resolved this issue based on discussions with other users. I'm closing this issue for now.
